01 lists
AndreyPanda/ru-study-python pull request #2
Opened 2023-03-10 14:50 UTC by AndreyPanda

Practice 2.4 "Lists" is completed - attempt #2 - the function for maximum element search is changed

2023-03-13 09:37 UTC, aleksandr-semenov-dbp requested changes

2023-03-13 09:37 UTC, aleksandr-semenov-dbp commented on lists/lists.py
> +            return []
по нашим правилам если есть короткая ветка if то лучше ее поставить первой, и если ветка if заканчивается return то не пишем else экономим отступ, такое немного легче читается. Т.е. здесь
```
if not input_list:
  return[]
max_elem = ...
```

2023-03-13 09:37 UTC, aleksandr-semenov-dbp commented on lists/lists.py
> +        else:
Здесь тоже это можно применить ^

2023-03-14 07:18 UTC, AndreyPanda commented on lists/lists.py
> +            return []
Принято, сейчас поправлю.

2023-03-14 07:22 UTC, closed without merging

2023-03-14 07:23 UTC, AndreyPanda commented
The changes in code are required by approving person. A new PR will be created.