Task 2.7 (Flask) is completed
AndreyPanda/ru-study-python pull request #6
Opened 2023-05-15 14:12 UTC by AndreyPanda

Task 2.7 (Flask) is completed

2023-05-17 07:46 UTC, aleksandr-semenov-dbp requested changes

2023-05-17 07:46 UTC, aleksandr-semenov-dbp commented on flask_exercises/flask_excercises.py
> +            if name in users.keys():
просто `name in users` (везде)

2023-05-18 03:24 UTC, AndreyPanda commented on flask_exercises/flask_excercises.py
> +            if name in users.keys():
Принято, спасибо за ревью!
Я внес изменения.

2023-05-29 12:33 UTC, kirill-gorshkov approved these changes

2023-05-30 07:11 UTC, merged